### ISSUE TITLE
create_virtualchest ignoring size on startup

### ISSUE THREAD

**Issue by PhanaticD** [EntityReborn/CHVirtualChests#18]
size reverts to 54 when create_virtualchest(@chest) is done on startup (from the example) even if the value in persistence is for example 9 for @chest['size']

doing create_virtualchest(@chest) from a player command alias does set it properly, but that ruins the whole point of having them load on startup

**Comment by PseudoKnight** [comment]
Can fix. It's in the to/from carray conversion.
